// languages.js - 游戏语言配置文件

const LANGUAGES = {
    'zh-CN': {
        // 菜单相关
        menu: {
            title: '游戏信息',
            totalTime: '游戏总时长',
            highestScore: '历史最高分',
            totalWheelCount: '合成轮子总数',
            currentScore: '当前游戏分数',
            settings: '游戏设置',
            gameMusic: '游戏音乐',
            gameSound: '游戏音效',
            language: '网页语言',
            restart: '重新开始',
            resetStats: '重置统计',
            about: '关于游戏',
            version: '合成大遗子 v2.0',
            hint: '提示：按 ESC 键可快速关闭菜单',
            confirmReset: '确定要重置所有游戏统计数据吗？此操作不可撤销。',
            resetComplete: '统计数据已重置！',
            aboutText: '合成大遗子 v2.0\n\n一个基于物理引擎的合成游戏\n素材来源：pixabay，爱给网，DOVA-SYNDROME，漫画本体\n\n祝您游戏愉快！'
        },
        // 游戏界面相关
        game: {
            title: '合成大遗子',
            score: '分数:',
            target: '目标:',
            next: '下一个:',
            restart: '重来',
            pause: '暂停',
            continue: '继续',
            instructions: '游戏说明',
            controlMove: '移动：',
            controlMouse: '鼠标',
            controlArrow: '方向键',
            controlDrop: '放下：',
            controlSpace: '空格键',
            controlDesc1: '控制下落的遗子碎片，将其放置在合适的位置',
            controlDesc2: '当两个相同的碎片接触时，会合成一个更大的遗子碎片',
            controlDesc3: '如果碎片堆到顶部的丝线，遗子被切开，游戏结束',
            reference: '合成表',
            gameOver: '游戏结束!',
            finalScore: '最终得分:',
            highestScore: '最高分:',
            watermelonCount: '你合成了',
            watermelonUnit: '个不可名状之物!',
            playAgain: '再玩一次',
            victoryTitle: '见证了不可名状之物的降临',
            victoryDesc: '你合成了???',
            victoryTime: '耗时:',
            victoryScore: '当前分数:',
            continueBtn: '继续',
            cashoutBtn: '结束',
            victoryHint: '提示: 继续合成可获得更高分数！',
            footer: '· 同人制作 ·',
            footer2: '素材来源：pixabay，爱给网，DOVA-SYNDROME，漫画本体'
        },
        // 水果名称
        fruits: ['剑突', '左手', '右腿', '左腿', '胯部', '上身', '头部', '"光"', '遗子', '？？？']
    },
    
    'en': {
        menu: {
            title: 'Game Info',
            totalTime: 'Total Play Time',
            highestScore: 'Highest Score',
            totalWheelCount: 'Total Yizi Count',
            currentScore: 'Current Score',
            settings: 'Game Settings',
            gameMusic: 'Game Music',
            gameSound: 'Game Sound',
            language: 'Language',
            restart: 'Restart Game',
            resetStats: 'Reset Statistics',
            about: 'About Game',
            version: 'Merge Yizi v2.0',
            hint: 'Hint: Press ESC to close menu',
            confirmReset: 'Are you sure you want to reset all game statistics? This cannot be undone.',
            resetComplete: 'Statistics have been reset!',
            aboutText: 'Merge Yizi v2.0\n\nA physics-based merge game\nResources from: pixabay, aigei.com, DOVA-SYNDROME, manga\n\nEnjoy the game!'
        },
        game: {
            title: 'Merge Yizi',
            score: 'Score:',
            target: 'Target:',
            next: 'Next:',
            restart: 'Restart',
            pause: 'Pause',
            continue: 'Continue',
            instructions: 'Game Instructions',
            controlMove: 'Move:',
            controlMouse: 'Mouse',
            controlArrow: 'Arrow Keys',
            controlDrop: 'Drop:',
            controlSpace: 'Spacebar',
            controlDesc1: 'Control the falling Yizi fragments and place them in suitable positions',
            controlDesc2: 'When two identical fragments touch, they merge into a larger Yizi fragment',
            controlDesc3: 'If fragments stack up to the top line, the Yizi is cut and the game ends',
            reference: 'Merge Chart',
            gameOver: 'Game Over!',
            finalScore: 'Final Score:',
            highestScore: 'Highest Score:',
            watermelonCount: 'You merged',
            watermelonUnit: 'unnameable entities!',
            playAgain: 'Play Again',
            victoryTitle: 'Witnessed the descent of the unnameable entity',
            victoryDesc: 'You merged ???',
            victoryTime: 'Time:',
            victoryScore: 'Current Score:',
            continueBtn: 'Continue',
            cashoutBtn: 'Cash Out',
            victoryHint: 'Hint: Continue merging for higher scores!',
            footer: '· Fan-Made ·',
            footer2: 'Resources from: pixabay, aigei.com, DOVA-SYNDROME, manga'
        },
        fruits: ['Sword', 'Left Hand', 'Right Leg', 'Left Leg', 'Pelvis', 'Upper Body', 'Head', '"Light"', 'Yizi', '???']
    },
    
    'ja': {
        menu: {
            title: 'ゲーム情報',
            totalTime: '総プレイ時間',
            highestScore: '最高得点',
            totalWheelCount: '総合体遺子数',
            currentScore: '現在の得点',
            settings: 'ゲーム設定',
            gameMusic: 'ゲーム音楽',
            gameSound: '効果音',
            language: '言語',
            restart: '再開',
            resetStats: '統計リセット',
            about: 'ゲーム情報',
            version: '合成大遺子 v2.0',
            hint: 'ヒント：ESCキーでメニューを閉じる',
            confirmReset: 'すべてのゲーム統計をリセットしますか？この操作は取り消せません。',
            resetComplete: '統計データをリセットしました！',
            aboutText: '合成大遺子 v2.0\n\n物理エンジンベースの合成ゲーム\n素材提供：pixabay、愛給網、DOVA-SYNDROME、漫画\n\nお楽しみください！'
        },
        game: {
            title: '合成大遺子',
            score: 'スコア:',
            target: '目標:',
            next: '次:',
            restart: 'リスタート',
            pause: '一時停止',
            continue: '続ける',
            instructions: 'ゲーム説明',
            controlMove: '移動：',
            controlMouse: 'マウス',
            controlArrow: '矢印キー',
            controlDrop: '落下：',
            controlSpace: 'スペースキー',
            controlDesc1: '落下する遺子の破片を操作し、適切な位置に配置してください',
            controlDesc2: '同じ破片が接触すると、より大きな遺子の破片に合成されます',
            controlDesc3: '破片が上部のラインまで積み上がると、遺子が切断されゲーム終了です',
            reference: '合成表',
            gameOver: 'ゲームオーバー!',
            finalScore: '最終得点:',
            highestScore: '最高得点:',
            watermelonCount: 'あなたは',
            watermelonUnit: 'つの名状しがたい存在を合成しました!',
            playAgain: 'もう一度遊ぶ',
            victoryTitle: '名状しがたい存在の降臨を目撃しました',
            victoryDesc: 'あなたは???を合成しました',
            victoryTime: '時間:',
            victoryScore: '現在の得点:',
            continueBtn: '続ける',
            cashoutBtn: '終了',
            victoryHint: 'ヒント: さらに合成して高得点を目指しましょう！',
            footer: '· ファン制作 ·',
            footer2: '素材提供：pixabay、愛給網、DOVA-SYNDROME、漫画'
        },
        fruits: ['剣', '左手', '右足', '左足', '腰', '上半身', '頭部', '「光」', '遺子', '？？？']
    }
};

// 导出语言配置
if (typeof module !== 'undefined' && module.exports) {
    module.exports = LANGUAGES;
}